# Generated by Django 5.1.6 on 2025-02-20 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('django', 'django'), ('spring boot', 'spring boot'), ('Hibernate', 'Hibernate'), ('React js', 'React js'), ('Mern', 'Mern'), ('Node JS', 'Node JS'), ('Next js', 'Next js'), ('Webtech', 'Webtech')], default='python', max_length=50)),
                ('communication', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50)),
                ('technical', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50)),
                ('programming', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('conducted_on', models.DateField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
