# Generated by Django 5.1.6 on 2025-02-26 11:49

import HR.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_alter_ratings_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduling',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student', models.FileField(upload_to=HR.models.scheduling.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('subject', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('django', 'django'), ('spring boot', 'spring boot'), ('Hibernate', 'Hibernate'), ('React js', 'React js'), ('Mern', 'Mern'), ('Node JS', 'Node JS'), ('Next js', 'Next js'), ('Webtech', 'Webtech')], max_length=100)),
                ('cource', models.CharField(choices=[('python fullstack development', 'python fullstack development'), ('java fullstack development', 'java fullstack development'), ('MERN fullstack development', 'MERN fullstack development'), ('Software Testing', 'Software Testing')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
