# Generated by Django 5.1.6 on 2025-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
